// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPmUvPYBaW4rRq8XxZoKKq4-jSiKdLgTM',
    appId: '1:700152334074:web:2f09747c08f1f20d396b43',
    messagingSenderId: '700152334074',
    projectId: 'gadget-world-3cf48',
    authDomain: 'gadget-world-3cf48.firebaseapp.com',
    storageBucket: 'gadget-world-3cf48.appspot.com',
    measurementId: 'G-Q4CPXTHLR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmiqelOzh9tWSewucIfH38N8AgJVTwcag',
    appId: '1:700152334074:android:31ef2adcb2dca4f5396b43',
    messagingSenderId: '700152334074',
    projectId: 'gadget-world-3cf48',
    storageBucket: 'gadget-world-3cf48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6H41n4wSRrzsvvJv0pskZ1w2Q6rVapFk',
    appId: '1:700152334074:ios:c707f6b4c3532fdc396b43',
    messagingSenderId: '700152334074',
    projectId: 'gadget-world-3cf48',
    storageBucket: 'gadget-world-3cf48.appspot.com',
    iosClientId: '700152334074-mgh1f91fledpo7cpm4qjdairqniigtfg.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );
}
